name: Build and release

on:
  workflow_dispatch:
    inputs:
      ghToken:
        description: 'GitHub Personal Access Token'
        required: true
      npmToken:
        description: 'NPM Access Token'
        required: true

jobs:
  # TESTING...
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up node
  #       uses: actions/setup-node@v2.1.1
  #       with:
  #         node-version: '12'
  #     - name: Cache
  #       uses: actions/cache@v2
  #       with:
  #         path: .yarn/cache
  #         key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-cache-
  #     - name: Install
  #       run: yarn install --immutable
  #     - name: Build
  #       run: yarn build
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: lib
  #         path: lib

  release:
    name: Release
    runs-on: ubuntu-latest
    # needs: [build] TESTING...
    steps:
      - name: Mask tokens
        run: |
          echo "🕶"
          echo "::add-mask::$INPUT_GHTOKEN"
          echo "::add-mask::$INPUT_NPMTOKEN"
      - name: Test token mask
        run: |
          echo "${{ github.event.inputs.ghToken }}"
          echo "${{ github.event.inputs.npmToken }}"
          echo "$INPUT_GHTOKEN"
          echo "$INPUT_NPMTOKEN"
      # TESTING...
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     token: ${{ github.event.inputs.ghToken }}
      #     fetch-depth: 0 # necessary for correct CHANGELOGS
      # - name: Set up node
      #   uses: actions/setup-node@v2.1.1
      #   with:
      #     node-version: '12'
      # - name: Cache
      #   uses: actions/cache@v2
      #   with:
      #     path: .yarn/cache
      #     key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-cache-
      # - name: Install
      #   run: yarn install --immutable
      # - name: Download artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: lib
      #     path: lib
      # - name: Release
      #   env:
      #     GH_TOKEN: ${{ github.event.inputs.ghToken }}
      #     NPM_TOKEN: ${{ github.event.inputs.npmToken }}
      #   run: yarn release
